// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QLPhongGym.Data;

#nullable disable

namespace QLPhongGym.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20260320080920_InitPostgres")]
    partial class InitPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QLPhongGym.Models.CheckIn", b =>
                {
                    b.Property<int>("MaCheckIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaCheckIn"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("MaHoiVien")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ThoiGianCheckIn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaCheckIn");

                    b.HasIndex("MaHoiVien");

                    b.ToTable("CheckIns");
                });

            modelBuilder.Entity("QLPhongGym.Models.DangKyGoiTap", b =>
                {
                    b.Property<int>("MaDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDangKy"));

                    b.Property<int>("MaGoiTap")
                        .HasColumnType("integer");

                    b.Property<int?>("MaHLV")
                        .HasColumnType("integer");

                    b.Property<int>("MaHoiVien")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaDangKy");

                    b.HasIndex("MaGoiTap");

                    b.HasIndex("MaHLV");

                    b.HasIndex("MaHoiVien");

                    b.ToTable("DangKyGoiTaps");
                });

            modelBuilder.Entity("QLPhongGym.Models.GoiTap", b =>
                {
                    b.Property<int>("MaGoiTap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaGoiTap"));

                    b.Property<decimal>("GiaTien")
                        .HasColumnType("numeric");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TenGoiTap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ThoiHanThang")
                        .HasColumnType("integer");

                    b.HasKey("MaGoiTap");

                    b.ToTable("GoiTaps");
                });

            modelBuilder.Entity("QLPhongGym.Models.HoiVien", b =>
                {
                    b.Property<int>("MaHoiVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaHoiVien"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaHoiVien");

                    b.ToTable("HoiViens");
                });

            modelBuilder.Entity("QLPhongGym.Models.HuanLuyenVien", b =>
                {
                    b.Property<int>("MaHLV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaHLV"));

                    b.Property<string>("ChuyenMon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaHLV");

                    b.ToTable("HuanLuyenViens");
                });

            modelBuilder.Entity("QLPhongGym.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("OtpCanResendAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OtpCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("OtpVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaTaiKhoan");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("QLPhongGym.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaThanhToan"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("MaDangKy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhuongThuc")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("numeric");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaDangKy");

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("QLPhongGym.Models.CheckIn", b =>
                {
                    b.HasOne("QLPhongGym.Models.HoiVien", "HoiVien")
                        .WithMany()
                        .HasForeignKey("MaHoiVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoiVien");
                });

            modelBuilder.Entity("QLPhongGym.Models.DangKyGoiTap", b =>
                {
                    b.HasOne("QLPhongGym.Models.GoiTap", "GoiTap")
                        .WithMany()
                        .HasForeignKey("MaGoiTap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLPhongGym.Models.HuanLuyenVien", "HuanLuyenVien")
                        .WithMany()
                        .HasForeignKey("MaHLV");

                    b.HasOne("QLPhongGym.Models.HoiVien", "HoiVien")
                        .WithMany()
                        .HasForeignKey("MaHoiVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoiTap");

                    b.Navigation("HoiVien");

                    b.Navigation("HuanLuyenVien");
                });

            modelBuilder.Entity("QLPhongGym.Models.ThanhToan", b =>
                {
                    b.HasOne("QLPhongGym.Models.DangKyGoiTap", "DangKyGoiTap")
                        .WithMany()
                        .HasForeignKey("MaDangKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DangKyGoiTap");
                });
#pragma warning restore 612, 618
        }
    }
}

